#!/usr/bin/env bash

declare -i salt=12345

file="data/quiz_data.csv"

# following line will find the first column, print it sorted with only unique lines, interating through each one
awk -F ',' '{print $1}' "$file" | sort -u | while read -r line; do

   #this variable is the salt before the raw data, before sha256sum
   saltedRawLine="$salt$line"

   #finds the hash of the salt + secred id and then prints it using echo
   hash=$(printf $saltedRawLine | sha256sum | awk '{print $1}')
   echo "$salt $line $hash"

   #then increment the salt to have unique salt for each instance of secret id
   salt+=1

   #next thing that needs done is adding sed command that replaces the 
   #instances of secret id with hash with salt prepended to it
done
